[keyboard]
bindings = [
{ key = 'H', mods = 'Control' , action = "Hide" },
{ key = 'M', mods = "Control|Shift", action = "Minimize" },
{ key = 'C', mods = "Control|Shift", action = "Copy" },
{ key = 'P', mods = "Control|Shift",  action = "Paste" },
{ key = 'N', mods = "Control|Shift", action = "CreateNewWindow"},
{ key = 'T', mods = "Control|Shift", action = "SpawnNewInstance"},
{ key = 'X', mods = "Control|Shift", action = "ClearHistory"},
{ key = 'Q', mods = "Control|Shift", action = "Quit"}
]
